[PF-109] initial RBS hello world spring APP
DataBiosphere/terra-rbs pull request #1
Opened 2020-09-23 15:31 UTC by yonghaoy

Cloned from kernel-service-poc repo

2020-09-23 16:32 UTC, wchamber requested changes
Consider whether we should create the shared library and start using that for RBS. That's a bigger task, but I think we should consider taking it on now. It only gets harder to do the more services we add first.
At least, let's update the poc with some of the improvements we've made to the janitor.

2020-09-23 16:32 UTC, wchamber commented on src/main/java/bio/terra/TEMPLATE/app/Main.java
> +package bio.terra.TEMPLATE.app;
should we go ahead and fix all the TEMPLATE in the initial commit?

2020-09-23 16:32 UTC, wchamber commented on src/main/java/bio/terra/TEMPLATE/app/configuration/ApplicationConfiguration.java
> +  private boolean dbUpgradeOnStart;
can we use the Janitor's variable naming? I find that more intuitive. Maybe we should contribute back to the kernel-poc.

2020-09-23 16:32 UTC, wchamber commented on src/test/resources/application.properties
> +server.port=8080
let's also use the yaml file and naming conventions that Greg changed to the Janitor. Also consider modifying POC first, then cloning.

2020-09-23 17:47 UTC, wchamber commented on src/main/java/bio/terra/TEMPLATE/app/configuration/ApplicationConfiguration.java
> +  private boolean dbUpgradeOnStart;
Also consider an enum with 3 values instead of 2 booleans with 3 valid combinations.

2020-09-23 20:11 UTC, yonghaoy commented on src/main/java/bio/terra/TEMPLATE/app/Main.java
> +package bio.terra.TEMPLATE.app;
ah, right. We can do it now

2020-09-24 21:21 UTC, yonghaoy commented on src/test/resources/application.properties
> +server.port=8080
done for rbs

2020-09-24 21:31 UTC, yonghaoy commented on src/main/java/bio/terra/TEMPLATE/app/configuration/ApplicationConfiguration.java
> +  private boolean dbUpgradeOnStart;
Changed to Janitor style. And for the enum vs booleans. I'd prefer do it later. There ares some things I am not sure yet:
1: How the config would looks like. Boolean is easier. And Enum would become String, and our configuration need extra logic about parsing string to enums and validation check.
2: What would be the 3 enum naming and meaning? Boolean with the javadoc is easer to understand, but naming enums to reflect the three things is challenging for me, I might need your help.
3: Not sure we need the 3): initialize is false; upgrade is false - do nothing to the database
Anyway, changed to Janitor structure for now?

2020-09-24 21:39 UTC, yonghaoy commented
Hi @wchamber I changed to Janitor as template with swager codegen, new config style, and all classes in the code.
And as synced offline, we will not modify poc code

2020-09-25 13:40 UTC, wchamber commented on src/main/java/bio/terra/TEMPLATE/app/configuration/ApplicationConfiguration.java
> +  private boolean dbUpgradeOnStart;
Leaving it alone sounds good. (I think Spring automatically tries to do Enum.valueOf from the string).

2020-09-25 13:50 UTC, wchamber approved these changes
Thanks!

2020-09-25 13:50 UTC, wchamber commented on build.gradle
> +    id 'com.google.cloud.tools.jib' version '2.5.0'
do we need the jib stuff somewhere (w/ or w/out the profiler agent stuff)? Totally fine to follow up in a later PR - just not sure this builds an image without it. Up to you.

2020-09-25 13:50 UTC, wchamber commented on src/main/resources/api/service_openapi.yaml
> +  - url: http://localhost:8080
This is different then the janitor where we have `- url: /`. I don't know which is supposed to be better.

2020-09-25 13:50 UTC, wchamber commented on README.md
> +local-dev/run_postgres.sh start
Add a todo to add the local-dev files to run the  postgres docker and run_local?

2020-09-25 13:57 UTC, yonghaoy commented on README.md
> +local-dev/run_postgres.sh start
Ah, sorry, I had those scripts in my local, the poc's `.gitignore` is not good. Updated `.gitginore` and uploaded all local-dev scripts

2020-09-25 14:27 UTC, yonghaoy commented on src/main/resources/api/service_openapi.yaml
> +  - url: http://localhost:8080
I think they are the same. Changed to `- url: /`

2020-09-25 14:28 UTC, yonghaoy commented on build.gradle
> +    id 'com.google.cloud.tools.jib' version '2.5.0'
I planed to add jib stuff when we add profiler agent later?

2020-09-25 14:28 UTC, merged