[PF-130] RbsDao supports retrieve pool with corresponding number of resources.
DataBiosphere/terra-rbs pull request #11
Opened 2020-10-07 17:33 UTC by yonghaoy

2020-10-07 17:41 UTC, wchamber requested changes

2020-10-07 17:41 UTC, wchamber commented on src/main/java/bio/terra/rbs/db/PoolAndResourceCount.java
> +  abstract int resourceCount();
maybe `int activeResources()`? (are we calling them ACTIVE or READY? class comment says "active." consistent terminology is nice again.)

2020-10-07 17:41 UTC, wchamber commented on src/main/java/bio/terra/rbs/db/RbsDao.java
> +                  .build(),
you could use a POOL_ROW_MAPPER here.

2020-10-07 17:41 UTC, wchamber commented on src/main/java/bio/terra/rbs/db/RbsDao.java
> +            + "(select count (*) from resource where pool_id = p.id) as resource_count "
this selects all resources counts, but `PoolAndResourceCount` talks about active resources. What do we want?
One thing we can do is have `PoolAndResourceCount` use a `Multiset<ResourceState>` to get counts of all the different resource states. Not sure what's going to be helfpul in the scheduler.

2020-10-07 17:41 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/FlightScheduler.java
> +public class FlightScheduler {}
optional nit: this file doesn't do anything yet.

2020-10-07 19:40 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/db/RbsDao.java
> +                  .build(),
Ah, right, thanks

2020-10-07 19:43 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/db/RbsDao.java
> +            + "(select count (*) from resource where pool_id = p.id) as resource_count "
I think we only cares about the READY resource state. So add a where clause should be enough?

2020-10-07 19:43 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/db/PoolAndResourceCount.java
> +  abstract int resourceCount();
Changed to activeResourcesCount

2020-10-07 19:48 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/db/PoolStatus.java
> +   * resources.
Modified by spotlessApply

2020-10-07 20:12 UTC, wchamber commented on src/main/java/bio/terra/rbs/db/RbsDao.java
> +            + "(select count (*) from resource where pool_id = p.id) as resource_count "
I'm not sure that's true for the scheduler. We don't want to overschedule resources if there are some resource creations in flight. i.e. we have 10 READY, 2 CREATING, for a pool of size 20. How many flights should we make?
We could make have 2 int fields, resourceReadyCount, resourceCreatingCount, but a `SetMultimap` might scale better.

2020-10-07 20:39 UTC, wchamber requested changes
I do think we need to know about the count of CREATING resources for scheduling. Isn't that what we're going to use PoolAndResourceCount for?

2020-10-07 20:39 UTC, wchamber commented on src/main/java/bio/terra/rbs/db/ResourceState.java
> +  HANDEDOUT,
nit: underscored two words, HANDED_OUT?

2020-10-07 20:42 UTC, wchamber commented on src/main/java/bio/terra/rbs/db/ResourceState.java
> +  HANDEDOUT,
also, I don't mind 'handed out' but it is a little awkward to use. any other naming ideas before we commit to the database forever? We could do "USED"? idk, no strong preference.

2020-10-07 22:17 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/db/RbsDao.java
> +            + "(select count (*) from resource where pool_id = p.id) as resource_count "
I think your are right. Updated the sql query and code little bit. PTAL Thanks

2020-10-07 22:20 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/db/ResourceState.java
> +  HANDEDOUT,
Okay, changed to used.

2020-10-07 23:11 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/db/RbsDao.java
> +        "select count (*) FILTER (WHERE r.state='READY') as ready_count, "
Not sure if this is the best approach, PTAL, thanks

2020-10-08 14:11 UTC, wchamber requested changes

2020-10-08 14:11 UTC, wchamber commented on src/main/java/bio/terra/rbs/db/RbsDao.java
> +        "select count (*) FILTER (WHERE r.state='READY') as ready_count, "
I think it's simpler if we get the counts for all of the resource states, even if we're not examining the handed out state yet. I think a GROUP BY r.state is also more idiomatic than using select subexpressions for each r.state value.
```
select count(*) as resource_count, r.state,
  p.id, p.resource_config, p.resource_type, p.creation, p.size, p.status
from pool p
join resource r on r.pool_id = p.id
group by p.id, r.state;
```
I think that works, but test to verify.
We do need to change the row mapper to be a ResultSetExtractor to group the resource state rows into a single object.
In Janitor, we do this to group the many rows of a TrackedResource with different label key/values into a single object per TrackedResource with all label values. So, not exactly what we're trying to do here, but similar. Let me know if you want to talk more.
https://github.com/DataBiosphere/terra-resource-janitor/blob/e4da842229aacd1e99bfcb1fffb9ac1eadb611dc/src/main/java/bio/terra/janitor/db/JanitorDao.java#L360-L381

2020-10-08 14:11 UTC, wchamber commented on src/main/java/bio/terra/rbs/db/ResourceState.java
> +  USED,
I really don't know if USED or HANDED_OUT is better. WDYT?

2020-10-08 14:23 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/db/ResourceState.java
> +  USED,
`USED` sounds wired. I vote for `HANDED_OUT`

2020-10-08 17:56 UTC, wchamber approved these changes

2020-10-08 17:56 UTC, wchamber commented on src/main/java/bio/terra/rbs/db/RbsDao.java
> +  public List<PoolAndResourceStates> retrievePoolAndResourceStatesCount() {
nit: `retrievePoolAndResourceStates()`

2020-10-08 19:22 UTC, merged