[PF-127] Create GCP projects
DataBiosphere/terra-rbs pull request #16
Opened 2020-10-13 15:37 UTC by yonghaoy

2020-10-13 19:34 UTC, wchamber requested changes

2020-10-13 19:34 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/FlightManager.java
> +  private CloudResourceManagerCow rmCow;
final?

2020-10-13 19:34 UTC, wchamber commented on src/main/java/bio/terra/rbs/db/RbsDao.java
> +    jdbcTemplate.update(sql, params);
maybe return a bool if anything was deleted?

2020-10-13 19:34 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateGoogleProjectStep.java
> +      Operation operation = rmCow.projects().create(project).execute();
I think you could run into a problem if this step gets when the project was already created. Maybe check that the project doesn't exist first?

2020-10-13 19:34 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateGoogleProjectStep.java
> +      logger.error("Error when creating GCP project", e);
I'm not sure this warrants `.error`: we expect this to happen some amount with GCP. Could logger.info, or just let our CRL logging take care of it.

2020-10-13 19:34 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateGoogleProjectStep.java
> +          .execute();
you should account for the project having failed to have been created.

2020-10-13 19:34 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/FinalCreateResourceStep.java
> +public class FinalCreateResourceStep implements Step {
think the name and comment are out of date. Maybe `ReadyResourceStep` or `FinishResourceCreationStep` or `MarkResourceReadyStep`?

2020-10-13 19:34 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/FinalCreateResourceStep.java
> +    // Nothing need to do.
worth explaining why. I think this is your doc that we shared with dan that there's nothing to do undo here because we either updated the RbsDao and are finished, or we didn't and we don't need to undo something. I think this is a little tricky and worth a longer comment.

2020-10-13 19:34 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/GenerateGoogleProjectIdStep.java
> +    // TODO(yonghao): Use Terra Project Id generator.
nit: make a ticket?

2020-10-13 19:34 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/GenerateGoogleProjectIdStep.java
> +public class GenerateGoogleProjectIdStep implements Step {
optoinal nit: I don't know that we need the `Google`. We don't have any other project ids, and when we start making more resources, their resource specific flights can end up in different packages.

2020-10-13 19:34 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/GenerateResourceIdStep.java
> +/** The step to create resourceId and put it in Stairway working map. state. */
nit: extra step?

2020-10-13 19:34 UTC, wchamber commented on src/main/resources/application.yml
> +    # to use Janitor in test.
I don't even know if I would include this since we're not setting anything

2020-10-13 19:34 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/RbsIntegrationTest.java
> +  // Currently
formatting?

2020-10-13 19:34 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/RbsIntegrationTest.java
> +  private static PoolId AOU_POOL_ID = PoolId.create("aou_ws_test_v1");
Hmmm, I don't know about using the auo_ws_test_v1 pool. I think I'd feel better if it wasn't associated with "aou" at all. Maybe just "ws_test_v1"? and `TEST_POOL_ID`?

2020-10-13 19:34 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/RbsIntegrationTest.java
> +  @Qualifier(GOOGLE_RM_COW)
Is there any way to not need these qualifiers? I don't think we want to have multiple CloudResourceManagerCows or Client configs floating around.

2020-10-13 19:34 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/RbsIntegrationTest.java
> +    List<Resource> resources = pollUntilResourceCreated(AOU_POOL_ID, 2, Duration.ofSeconds(10), 10);
It's really odd to me that this test doesn't initiate the resource creation in anyway. Is it happening automatically by virtue of the server starting up? That seems really dangerous for testing where we might restart the server many times for any given test.

2020-10-13 20:34 UTC, yonghaoy commented on src/main/resources/application.yml
> +    # to use Janitor in test.
I thought I have it here with the comment as a reminder not to forget to set those values in test, especially when other servers take the code as an example to use CRL?

2020-10-14 13:31 UTC, yonghaoy reviewed
@wchamber Hi Will, comments are addressed, there are some open questions left. Happy to chat offline. 
Also add a test for verify ResourceCreation in data base's rollback. 
PTAL. Thanks

2020-10-14 14:54 UTC, wchamber commented on src/main/java/bio/terra/rbs/db/PoolId.java
> +@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.WRAPPER_ARRAY)
We don't need to use Gson in the middle. `create` is the function for serializing from a string.
```
class PoolId {
  private static final String POOL_ID_MAP_KEY "poolIdKey";
  static PoolId retrieve(FlightMap map) {
       return PoolId.create(map.get(POOL_ID_MAP_KEY, String.class);
  }
  FlightMap store(FlightMap map) {
    map.put(POOL_ID_MAP_KEY, id());
    return map;
  }
```
I think the FlightMapKeys pattern is awkward. It divorces the keys from what they serialize. You can't just look at the keys and figure out how to `map.put` and `map.get`; you have to go look at an existing usage. Defining the flight map key next to to the functions about how to `put` and `get` encapsulates that logic in a single place.
Not going to die on this hill, but I'd prefer explicit to implicit serialization into FlightMap .

2020-10-14 15:02 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateGoogleProjectStep.java
> +      Operation operation = rmCow.projects().create(project).execute();
Sorry, I didn't mean duplication, I meant retries of this step. Let's say we create the project, but fail out polling the operation. Now we retry this step, and fail to create the project because we already created it, and we have to abort the step altogether.

We can write a helper function that does the 403 interpreting correctly, e.g. https://github.com/DataBiosphere/terra-workspace-manager/blob/1322b1cf98e094f0b68cf38b3c1db38e5655ccec/src/main/java/bio/terra/workspace/service/workspace/flight/CreateProjectStep.java#L73-L84

2020-10-14 15:09 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateGoogleProjectStep.java
> +      logger.error("Error when creating GCP project", e);
I strongly disagree. That's relying on us to look at the log and care about the volume of this error because it's obscuring other important errors. We don't actually care about this step failing, we care about it failing frequently. The right way to alert for that is custom metrics looking at step success rate, or probably flight failure rate. And what's "frequent enough for us to care?" 1/minute? 1/10 steps?
Error means somebody should care about looking at this log. This is more like it was interesting that the step failed, but that's expected behavior. go/java-logging-best-practices#logging-levels-and-avoiding-spam https://g3doc.corp.google.com/base/g3doc/logging.md?cl=head#c-logging-levels

2020-10-14 15:10 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateGoogleProjectStep.java
> +          .execute();
No, the undo starts on the same step. Otherwise a step would have to know about the actions of the subsequential step.
In undo, we need to be prepared for the `do` to have failed at any point, or even succeeded.

2020-10-14 15:11 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/GenerateGoogleProjectIdStep.java
> +public class GenerateGoogleProjectIdStep implements Step {
YAGNI. Start simple, then add more disambiguation as needed. A rename isn't hard, but in the meantime the longer name takes up more space and eye-time.

2020-10-14 15:31 UTC, wchamber requested changes
Next time break it up before sending it out. 900 lines is too much. Possible pieces you could have done for this PR.
* config changes including rendering.
* RbsDao changes.
* Related steps, but not the whole flight, e.g. the resource id generation and store in dao steps. or the project id creation and project creation steps.

2020-10-14 15:31 UTC, wchamber commented on README.md
> +* A Google Service Account Secret to publish message to 'prod' Janitor instance.
nit: remove 'prod', just publish to a Janitor instance.

2020-10-14 15:31 UTC, wchamber commented on src/main/java/bio/terra/rbs/app/configuration/CrlConfiguration.java
> +  /** Credential file path to be able to publish message to Janitor test env (toolsalpha). */
not `toolsalpha`. finish fixing this comment.

2020-10-14 15:31 UTC, wchamber commented on src/main/java/bio/terra/rbs/app/configuration/CrlConfiguration.java
> +  private String janitorTrackResourceTopicId;
I think it's worth noting that we only use these fields when `testingMode` is true.

2020-10-14 15:31 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/FlightManager.java
> +  public Optional<String> submitCreationFlight(Pool pool) {
needs a comment about what this does and what the return type is.

2020-10-14 15:31 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/FlightManager.java
> +    flightMap.put(FlightMapKeys.RESOURCE_CONFIG, pool.resourceConfig());
I'd kind of rather this happens as a part of the flightFactory, like Janitor where the Flight class is also allowed to set up the FlightMap. Then we can have a static function on the Flight class for initializing the Flight map. Otherwise, this code that sets up the FlightMap is far away from the steps that care about the input FlightMap.
https://github.com/DataBiosphere/terra-resource-janitor/blob/master/src/main/java/bio/terra/janitor/service/cleanup/FlightSubmissionFactoryImpl.java#L14-L19

2020-10-14 15:31 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/FinishResourceCreationStep.java
> + * state.
fix the comment

2020-10-14 15:31 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/FinishResourceCreationStep.java
> +    // Nothing need to do.
still need to expand on this, see previous PR review comment on same line.

2020-10-14 15:31 UTC, wchamber commented on src/test/java/bio/terra/rbs/db/PoolIdTest.java
> +/** Unit tests to verify {@link PoolId} is serializable/deserializable by Jackson. */
It's not just that's its serializable. We critically need to maintain backwards compatibility since this gets stored in Stairway's database. Include that in the comment and the deserialize test function name.

2020-10-14 15:31 UTC, wchamber commented on src/test/java/bio/terra/rbs/db/RbsDaoTest.java
> +    rbsDao.deleteResource(resource.id());
`assertTrue(rbsDao.deleteResource...`

2020-10-14 15:31 UTC, wchamber commented on src/test/java/bio/terra/rbs/db/ResourceIdTest.java
> +/** Unit tests to verify {@link ResourceId} is serializable/deserializable by Jackson. */
ditto

2020-10-14 15:31 UTC, wchamber commented on src/test/java/bio/terra/rbs/service/resource/FlightManagerTest.java
> +  public void undoCreateResourceEntityStep_shouldDeleteDbRecord() throws Exception {
I don't see why this is a FlightManager test. It seems like it's testing a single step.

Can we test all of the project creation steps individually? Or the project creation flight class directly? Or at least all of the project creation flight class steps together with interspsersed latch and error?
I don't think this is doing a good job of testing do/undo for the flight.

2020-10-14 20:09 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/db/PoolId.java
> +@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.WRAPPER_ARRAY)
I see what you mean. Changed to the way you suggest. But I also keep the Jackson annotations because I thought that is something good to have to let Jackson seralize/deseralize autovalue object?

2020-10-15 16:31 UTC, wchamber commented on src/main/java/bio/terra/rbs/db/PoolId.java
> +/** Wraps the id in db pool table. */
nit: not new, but maybe - `The unique identifier for every Pool.`
it's not just about what's in the db.

2020-10-15 16:31 UTC, wchamber commented on src/main/java/bio/terra/rbs/db/PoolId.java
> +@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.WRAPPER_ARRAY)
I don't think we should have jackson annotations we're not using. That's confusing until we need them. We're not using jackson with the FlightMap functions, so let's remove them (and the builder) for now.

2020-10-15 16:46 UTC, wchamber requested changes

2020-10-15 16:46 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/FlightManager.java
> +    flightMap = pool.id().store(flightMap);
we don't need the re-assignment. We're only returning the flightMap so that it can be used fluently, e.g.
`pool.id().store(flightMap).put(FlightMapKeys.RESOURCE_CONFIG, poolresourceConfig();`
The input flight map is mutated.
maybe just stop returning the FlightMap if that doesn't seem very helpful.

2020-10-15 16:46 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateGoogleProjectStep.java
> +    } catch (IOException | RetryException e) {
I don't think you want to catch a RetryException and re-wrap it in a retry StepResult. It's ok to not catch the Retry and allow the doStep to throw RetryException.
as-is, you're double wrapping exceptions.
The other approach would be to have pollUntilSuccess throw IOExceptoin | InterruptedException then wrap them both here.

2020-10-15 16:46 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/FinishResourceCreationStep.java
> +    // from db. Both steps are handled in previous steps undo method.
Actually, don't we want to put something in the workingMap after we've updated the resource as READY and check that in *every* undo step before deleting anything? I thought that was how we were going to avoid handing out a resource and then deleting it.
This PR or the next, worth checking that behavior.

2020-10-15 16:46 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/GoogleProjectCreationFlight.java
>      addStep(new CreateGoogleProjectStep(rmCow, gcpProjectConfig), retryRule);
I guess I'll make the same argument that this should be `CreateProjectStep`

2020-10-15 16:46 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/RbsIntegrationTest.java
> +    poolService.updateFromConfig(loadPoolConfig("test/config"), transactionStatus);
uh, what's up with the null transactionStatus? worth a comment about what's going on at aleast.

2020-10-15 16:46 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/RbsIntegrationTest.java
> +    String flightId = manager.submitCreationFlight(pool).get();
the first test in this class tests that the pools are filled automatically. This test is about how the CreateProjectFlight reacts to an error. I think these should be in different classes. Maybe add a `CreateProjectFlightIntegrationTest`?

2020-10-15 16:46 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/RbsIntegrationTest.java
> +      TimeUnit.MILLISECONDS.sleep(pollMs);
nit: define your variable as a Duration instead of an int and convert it to an int for the sleep. Always prefer Duration objects to primitive int values.
```
Duration poll = Duration.ofMillis(100);
TimeUnit.MILLISECONDS.sleep(poll.toMillis())
```

2020-10-15 16:46 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/RbsIntegrationTest.java
> +    assertFalse(rbsDao.retrieveResource(resource.id()).isPresent());
check the project is being deleted?

2020-10-15 18:25 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/resource/FlightManager.java
> +    flightMap = pool.id().store(flightMap);
Let store return void instead.

2020-10-15 18:39 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/integration/RbsIntegrationTest.java
> +    assertFalse(rbsDao.retrieveResource(resource.id()).isPresent());
The project is never created. We want to verify the rollback can success even project doesn't exist.
Also, it's hard to get generated project id, ResourceUid is populated at the end of the flight. 
So I only verify the entire flight rollback successfully(by checking db).

2020-10-15 18:45 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/integration/RbsIntegrationTest.java
> +    String flightId = manager.submitCreationFlight(pool).get();
Done

2020-10-15 18:47 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/integration/RbsIntegrationTest.java
> +    poolService.updateFromConfig(loadPoolConfig("test/config"), transactionStatus);
Added some comment above and rename it.

2020-10-15 18:53 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/resource/flight/FinishResourceCreationStep.java
> +    // from db. Both steps are handled in previous steps undo method.
Okay, I will improve it here in next PR. Just to confirm. If resource state is handout, we will return fatal in undo?

2020-10-15 19:53 UTC, wchamber requested changes

2020-10-15 19:53 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateProjectStep.java
> +    } catch (IOException | InterruptedException | RetryException e) {
don't catch `RetryException`?

2020-10-15 19:53 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/IntegrationUtils.java
> +      int maxNumPolls)
6 arguments is too many. Can we just use default values for `period` and `maxNumPolls`? Do these really need to vary? 
Let's put the `int expectedResourceNum` next to the `ResourceState`. Or do we want to use a Multiset<ResourceState> or a Map<ResourceState, Integer>? 
`pollUntilResourceExists` doesn't sound like it's examining the `ResourceState`. maybe `pollUntilResourcesMatch` ? `pollUntilResourceCountsAre`?

2020-10-15 19:53 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/RbsIntegrationTest.java
> +  TransactionStatus unusedTransactionStatus;
This smells weird to me. It's a PoolService implementation detail that the transactionStatus can be null. Maybe we should instead annotate the PoolService methods with `@Transactional` probably work for a follow up PR. Does this look odd to you?
if we're never initializing it, maybe just inline it as null.

2020-10-15 19:53 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/RbsIntegrationTest.java
>        throws Exception {
duplicated by IntegrationTestUtils?

2020-10-15 19:53 UTC, wchamber commented on src/test/java/bio/terra/rbs/service/resource/flight/ErrorCreateProjectStep.java
> +public class ErrorCreateProjectStep extends CreateProjectStep {
Can we include this in the test file where it's used? I don't think we should need to have this in multiple test files...

2020-10-15 19:53 UTC, wchamber commented on src/test/java/bio/terra/rbs/service/resource/flight/ErrorCreateProjectStep.java
> +/** Dummy {@link CreateProjectStep} which fails in doStep. */
`but still runs undoStep?`

2020-10-15 19:53 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/FinishResourceCreationStep.java
> +    return StepResult.getStepResultSuccess();
(can't figure out how to reply to the comment chaing)
You tell me what your doc says to do. At least TODO the ticket to implement this correctly.

2020-10-15 19:53 UTC, wchamber commented on src/test/java/bio/terra/rbs/service/resource/flight/LatchStep.java
> + * restart. It is only useful for testing.
probably still good to have. we might want some stairway-contrib-testing-utils one day.

2020-10-15 20:06 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/integration/IntegrationUtils.java
> +      int maxNumPolls)
make period and maxNumPolls constant now. 
And put the int expectedResourceNum next to the ResourceState.
I didn't merge those in `Map` or `Multiset` because I think the method only need to check single state. Add those extra logic to process Map in caller and here is unnecessary. `Pair` would be a good option through...

2020-10-15 20:13 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/integration/RbsIntegrationTest.java
> +  TransactionStatus unusedTransactionStatus;
Inlined as null for now here. 
I thought TransactionalStatus might be helpful if we want it. But seems we are not using that one for now. Will check with you offline about how we will future change the poolService's transactional method stuff later as follow up

2020-10-15 20:23 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/resource/flight/FinishResourceCreationStep.java
> +    return StepResult.getStepResultSuccess();
Added a TODO for now. I can not create ticket under any epics now. I will create a ticket then once that issue is resolved and when I worked on it. 
BTW, can you still create tickets under Janitor/RBS epic?

2020-10-15 21:27 UTC, wchamber approved these changes

2020-10-15 21:27 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/FinishResourceCreationStep.java
> +    // TODO(yonghao): Fail the flight if resource is already handed out.
just TODO(PF-127). We're not done with Stairway project creation until undo works correctly.

2020-10-15 21:37 UTC, merged