[PF-183] Billing info setup
DataBiosphere/terra-rbs pull request #21
Opened 2020-10-16 17:23 UTC by yonghaoy

2020-10-16 17:23 UTC, yonghaoy commented
Actually we need to enable billing api for the project we are using in test. Having a terraform for that...

2020-10-16 19:07 UTC, wchamber requested changes

2020-10-16 19:07 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/GoogleProjectCreationFlight.java
> +      addStep(new SetBillingInfoStep(billingCow, gcpProjectConfig));
maybe always add the step and check in the step if anything needs to be done based on the gcpProjectConfig? That might be a little simpler for us to debug Stairway things which care about the number of steps.

2020-10-16 19:07 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/SetBillingInfoStep.java
> +/** Creates the basic GCP project. */
update

2020-10-16 19:07 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/RbsIntegrationTest.java
>      assertEquals("ACTIVE", project.getLifecycleState());
group the project get with the project lifecycle assertion - don't have the billing check in the middle.

2020-10-16 19:07 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/RbsIntegrationTest.java
> +            .getBillingAccountName());
we're starting to get more detailed about checking that the project creation flight creates the project in the correct way. I think that kind of check is more appropriate for the `CreateProjectFlightIntegrationTest`. I also want a test that having a null billing account still allows a project to be created.

The tests in this file are just about the end2end, not the particulars how created projects.

2020-10-16 19:46 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/resource/flight/GoogleProjectCreationFlight.java
> +      addStep(new SetBillingInfoStep(billingCow, gcpProjectConfig));
done

2020-10-16 20:19 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/integration/RbsIntegrationTest.java
> +            .getBillingAccountName());
okay, moved to CreateProjectFlightIntegrationTest.

2020-10-16 20:25 UTC, wchamber requested changes

2020-10-16 20:25 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/pool/PoolWithResourceConfig.java
> +   abstract ResourceConfig resourceConfig();
nit: it's funny that this class is public but it's methods are package private. I know they aren't currently used somewhere, but maybe keep them public for simplicity and so we don't have to change it later?

2020-10-16 20:25 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/SetBillingInfoStep.java
> +      return StepResult.getStepResultSuccess();
uh, this looks backwards to me. Shouldn't we skip if the billing account is null or is an empty string?
How are the tests passing? Am I reading this wrong?

2020-10-16 20:25 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
> +    Pool pool = preparePool(newBasicGcpConfig().billingAccount(BILLING_ACCOUNT_NAME));
the basic project has a billing account, so we need a test for one without a billing account

2020-10-16 20:25 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
> +    }
nit: I think it'd be better to turn this into multiple asserts. I don't like the conditional asserting based on input parameters - that's too much logic for a test assertion.
maybe `void assertProjectExists(Resource resource)` and `assertBillingIs(Resource resource, String billingAccount)`?

2020-10-19 12:34 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/resource/flight/SetBillingInfoStep.java
> +      return StepResult.getStepResultSuccess();
oh, right. Test does fails actually. Test passing now...

2020-10-19 12:36 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
> +    Pool pool = preparePool(newBasicGcpConfig().billingAccount(BILLING_ACCOUNT_NAME));
changed here to: Basic doesn't have billing account. We only set billing account in this test here.

2020-10-19 15:26 UTC, wchamber approved these changes

2020-10-19 15:26 UTC, wchamber commented on terra-rbs-client/build.gradle
> +plugins {
uh, I think adding the `terra-rbs-client/build.gradle` should be a separate PR. Please remove. Careful with your commits and branches.

2020-10-19 15:38 UTC, yonghaoy commented on terra-rbs-client/build.gradle
> +plugins {
ah, strange, it is in his PR. My local branchs got messed up somehow. Removed

2020-10-19 15:45 UTC, merged