[PF-131] Add handout endpoint api interface
DataBiosphere/terra-rbs pull request #28
Opened 2020-10-21 01:43 UTC by yonghaoy

2020-10-21 14:15 UTC, wchamber requested changes

2020-10-21 14:15 UTC, wchamber commented on src/main/resources/api/service_openapi.yaml
> +    get:
should this be a `put` (or maybe `post`?) since we're modifying state? I think the request id should also be a path parameter because REST likes to encode parameters that identify a resource in the path instead of query or body.

2020-10-21 14:15 UTC, wchamber commented on src/main/resources/api/service_openapi.yaml
> +          description: OK
Explain the semantics of using the same request id multiple times.

2020-10-21 14:15 UTC, wchamber commented on src/main/resources/api/service_openapi.yaml
> +      summary: Get a resource from pool.
there's a little more going on here. the request id is assigned to the resource no more than once, we hand it out, etc.

2020-10-21 14:28 UTC, yonghaoy commented on src/main/resources/api/service_openapi.yaml
> +    get:
Changed to put and path params.
But put also feels wired, 
From client point, it is getting resource from RBS, and updating state is some internal side effect in RBS? But from the logical operation, put also make sense because we are modifying resource?

2020-10-21 14:52 UTC, wchamber commented on src/main/resources/api/service_openapi.yaml
> +    get:
If we think about it as the client putting a resource reservation in RBS, I think it's ok. It's definitely not a `get` because it's not a read, the client wants something to change. Yeah, this is more of an RPC than a REST endpoint, but whatever.

2020-10-22 15:10 UTC, wchamber approved these changes

2020-10-22 15:10 UTC, wchamber commented on src/main/resources/api/service_openapi.yaml
> +          description: OK, using the same handoutrequestId will also get 200 back with the same ResourceInfo.
nit: camelcase s/handourequestId/handoutRequestId

2020-10-22 15:10 UTC, wchamber commented on src/main/resources/api/service_openapi.yaml
>          The identity present by client when asking for a resource. Using the same handoutRequestId in the same pool would ge the same resource back.
nit: The unique identifier presented by the client for a resource request. Using the same...

2020-10-22 15:18 UTC, merged