[PF-163] Create sub network support
DataBiosphere/terra-rbs pull request #34
Opened 2020-10-23 16:17 UTC by yonghaoy

2020-10-23 18:02 UTC, wchamber requested changes

2020-10-23 18:02 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
> +      addStep(new FinishResourceCreationStep(rbsDao));
this is not really maintainable. This is supposed to be the same sequence of steps as the normal creation flight, but it's just copy-pasted and nothing is checking that. Figure out how to make this stay in sync.

2020-10-23 18:06 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateSubnetsStep.java
> +public class CreateSubnetsStep implements Step {
I think Google also calls it subnets: https://cloud.google.com/vpc/docs/vpc#vpc_networks_and_subnets

2020-10-23 18:14 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateSubnetsStep.java
> +  public static String generateIpRange(int i) {
My understanding: 
Some valid ipV4 ranges: https://cloud.google.com/vpc/docs/vpc#manually_created_subnet_ip_ranges
For us, it is from 10.128.0.0/20 to 10.176.0.0/20 for now. 
And seems that is the values in DM:
https://console.cloud.google.com/dm/deployments/details/dm-aou-rw-test-aa8646c7?project=terra-deployments-dev&folder&organizationId

@gjuggler for more information.

2020-10-23 18:28 UTC, gjuggler commented on src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
> +    // Verify flight is able to finish successfully when subnets exists
I think you need to add a bit more explanation to this test case. IMO it's important to mention that this scenario may arise when the step partially fails and ends up in a state where some subnets need to be recreated and some are getting created the first time.

2020-10-23 18:28 UTC, gjuggler commented on src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
> +  private void assertSubnetsExists(Project project, boolean networkMonitoringEnabled)
sp / grammar nit: s/exists/exist/

2020-10-23 18:28 UTC, gjuggler commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateSubnetsStep.java
> +  public static final List<String> SUBNETS_REGIONS =
See my suggested javadoc comments. tl;dr I agree it's not maintainable if we care about having all possible regions reflected here. However, the other extreme (only create a subnet in Terra's current "primary" region) is almost certainly less preferable in the medium term. So this is a balance, to create some future flexibility in resource regions while not going overboard on infrastructure yet (since we don't have a pressing product need).

For example: it's not hard to imagine some cron job which periodically crawls projects and adds missing subnet regions – if we end up needing something like that.

2020-10-23 18:28 UTC, gjuggler commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateSubnetsStep.java
> +  public static String generateIpRange(int i) {
See the javadoc comment I suggest above – the scheme in the DM code was meant to replicate the empirical behavior of Google's default network and auto-subnet creation. That said, I implemented that awhile ago, so if Google's IP allocation has changed, maybe we need to think more on this.

2020-10-23 19:56 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateSubnetsStep.java
> +      // Batch poll to make it faster
ah, right, change the comment to make it clearer

2020-10-23 20:27 UTC, yonghaoy reviewed
Thanks! Comments are addressed, PTAL!

2020-10-23 20:27 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateSubnetsStep.java
> +  public static String generateIpRange(int i) {
Thanks!, Greg, a question(happy to discuss in person): 
If DM tried to replicate the behaviour of auto-subnet, I don't think it ever matches the default ip rage. https://cloud.google.com/vpc/docs/vpc#ip-ranges (region-ip pair).
And the list here even missed some regions, like asia-northeast3,  asia-southeast2, us-west3, us-west4.

2020-10-23 20:27 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
> +      addStep(new FinishResourceCreationStep(rbsDao));
as long as we added CreateSubnetsStep() twice and test passed, we are good. It's necessary to be the same sequence of steps as the normal creation, we have those steps because it is the easiest way to **setup**. i.e., we need billing, compute api, and a network to create subnet. We can remove IAM policy because we don't need it.
I think the problem is code duplication, but I don't know what is the best way of decup the code from CreationStep. Any suggestion?

2020-10-23 20:27 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
> +    Network network = computeCow.networks().get(project.getProjectId(), NETWORK_NAME).execute();
we need to verify the subnet selflink line below

2020-10-23 20:27 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
> +      assertEquals(generateIpRange(i), subnetwork.getIpCidrRange());
Changed to use a Map<Region, Ip> now. PTAL

2020-10-23 20:27 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
> +  private void assertSubnetsExists(Project project, boolean networkMonitoringEnabled)
I don't want to add two more functions like 
assertNonMornitorSubnet()
assertMornitorSubnet()
assertSubnetInternal()
The test files is getting more complicated now.   I'd like to use boolean with  inlined /**comment*/ in callsiet ...

But I changed to pass Network config instead. Does that LG?

2020-10-23 20:27 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateSubnetsStep.java
> +            // do nothing
the part is gone now

2020-10-23 20:27 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateSubnetsStep.java
> +/** Craetes Subnetworks for project */
Thanks!

2020-10-23 22:32 UTC, gjuggler commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateSubnetsStep.java
> +  public static String generateIpRange(int i) {
I clearly didn't look hard enough for that list when I first set up that scheme :) Let's anchor to the actual auto-mode IP ranges. Thanks Will for questioning this.

The missed regions were likely all added since the DM work first began, e.g. us-west3 and us-west4 seem to have been launched in 2020. This highlights the fundamental "flaw" in this approach, but it's a price we're paying to align with CIS best practices, which was a hard requirement for AoU to adopt Terra.

2020-10-23 22:57 UTC, gjuggler commented on src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
> +      addStep(new FinishResourceCreationStep(rbsDao));
Here's my cheeky attempt. Seems like it compiles, but I couldn't actually run integration tests to check it works. (I'm getting a 403 trying to pull secrets from Vault. I'll need to chase that down another time.)

```
  public static class MultiSubnetsStepFlight extends GoogleProjectCreationFlight {

    public MultiSubnetsStepFlight(FlightMap inputParameters, Object applicationContext) {
      super(inputParameters, applicationContext);
    }
    
    @Override
    protected void addStep(Step step) {
      super.addStep(step);
      if (step instanceof CreateSubnetsStep) {
        // Create a duplicate entry for any CreateSubnetsStep in the original flight path.
        super.addStep(step);
      }
    }
  }
```

It's obviously not a very flexible way to edit the step list for a pre-existing flight, though. Adding a  `flight.insertStepForTestingOnly(index, step)` method to Stairway might be more generally suitable. Or otherwise some Stairway-level control mechanism which simulates partial step failure and retry, though that would probably require some deeper thought.

2020-10-23 22:59 UTC, gjuggler approved these changes
LGTM, but I'd treat Will's approval as the authoritative one here :)

2020-10-26 13:15 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
> +      addStep(new FinishResourceCreationStep(rbsDao));
Thanks!

2020-10-26 13:51 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateSubnetsStep.java
> +  public static String generateIpRange(int i) {
Changed to use region - ip range map. Unfortunately, I have to manually copy them over..

2020-10-26 14:18 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
> +  private void assertSubnetsExists(Project project, boolean networkMonitoringEnabled)
No, passing the whole Network config makes the test more difficult to understand - it could do anything with the network config, why does it need the whole thing.
If the extra functions seem too heavy weight, how about an enum? 
```
enum NetworkMonitoring { ENABLED; DISABLED }
...
assertSubnetExists(project, NetworkMonitoring.ENABLED);
```
If the enum is also too much, let's at least do argument comments, `assertSubnetExists(project, /*networkMonitoringEnabled= */ true);
https://goto.google.com/java-practices/boolean-parameters

2020-10-26 14:31 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
> +  private void assertSubnetsExists(Project project, boolean networkMonitoringEnabled)
done

2020-10-26 14:52 UTC, wchamber requested changes
Last touches. I think the comment additions and REGION_TO_IP_RANGE map are really good changes.

2020-10-26 14:52 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/GoogleUtils.java
> +  public static boolean cloudObjectExists(CowExecute execute) throws IOException {
Nice idea. Few suggestions.

The function name seems a little redundant given this is under `GoogleUtils`. Is `objectExists()` going too far? (I also kind of want to call them resources, `resourceExists()`) WDYT? Not sure what's better.

Let's add a little to the javadoc.
```
<p>Many Google 'get' operations return a {@link GoogleJsonResponseException} 404. This function handles that exception case as false, while throwing any other exception.
```

2020-10-26 14:52 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/GoogleUtils.java
> +    void execute() throws IOException;
This needs javadoc. Add `@FunctionalInterface` for as well.
I'm not convinced `Cow` is super relevant here, but maybe some Javadoc will make it seem better.

2020-10-26 14:52 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/GoogleUtils.java
> +      return true;
should we return an Optional<R> instead of boolean? Then we can re-use this where we get project check for existence.
I guess we could have two helper functions, and have the boolean one `return isPresent` the Optional one. Seems like a common pattern. WDYT?

2020-10-26 14:52 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateSubnetsStep.java
> +      // Kicking off all the operations first then polling all operations.
nit: `then poll all operations`

2020-10-26 14:52 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateSubnetsStep.java
> +    // doStep methods already checks Sunets exists or not. So no need to delete subnet.
typo `Sunets`

2020-10-26 14:52 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/GoogleUtils.java
> +        && gcpProjectConfig.getNetwork().isEnableNetworkMonitoring();
yay null values. When I see this nonsense, I kind of want to convert our Json config into an AutoValue. Don't do anything in this PR, I'm just bloviating.

2020-10-26 14:52 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
> +    // Basic GCP project with billing setup.
+1

2020-10-26 14:52 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
> +    assertEnableApisContains(project, pool.resourceConfig().getGcpProjectConfig().getEnabledApis());
I think it's also ok to remove assertions not relevant to the test. We don't need to assert everything about every test. It's not likely that enabling network monitoring is going to disable billing or the apis. As-is, there's extra boilerplate that makes it harder to find out what this test actually cares about, e.g. the network/subnets with their monitoring.
In the basic test, asserting everything is as it should be is good, but we don't need to repeat that for every special case.
(ditto all other tests)

2020-10-26 14:52 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
> +    // recreated and some are getting created the first time.
nit: whitespace

2020-10-26 14:52 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
> +  public static class MultiSubnetsStepFlight extends GoogleProjectCreationFlight {
looks like a general pattern that's useful for testing. Can we parameterize it so that we only need 1 class and not many?
```
public static class MultiInstanceStep<T extends Step> extends GoogleProjectCreationFlight {
...
  if (step instanceof T)
...
```
bonus points if you can also parameterize/generalize for other flights and not just subclass `GoogleProjectCreationFlight`.

2020-10-26 15:18 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/resource/flight/GoogleUtils.java
> +    void execute() throws IOException;
added a javadoc. Stilling using CowExecute because I am not sure what would be a better name. maybe `CloudExecute`?

2020-10-26 15:37 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/resource/flight/GoogleUtils.java
> +      return true;
I don't think we can use it for getting project because that is 403.
For other things, I use the new Optional function now

2020-10-26 15:39 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/resource/flight/GoogleUtils.java
> +        && gcpProjectConfig.getNetwork().isEnableNetworkMonitoring();
That would interesting... This config is defined/generated by openapi and parsed by Jackson... Now sure when/where we can plug autoValue in

2020-10-26 15:59 UTC, gjuggler commented on src/main/java/bio/terra/rbs/service/resource/flight/GoogleUtils.java
> +        && gcpProjectConfig.getNetwork().isEnableNetworkMonitoring();
We struggled with this in AoU as well. All of the swagger-generated classes are simply defined with template code; in theory it should be possible to improve those templates to have better / more fluent handling of nulls like this, but that involves reaching pretty deep into the internals of those templates, so we never bit the bullet on it.

One example of where we did end up doing some template-hacking was to add universal tracing to our server-side OpenAPI classes ([code](https://github.com/all-of-us/workbench/blob/master/api/src/main/resources/swagger3codegen/libraries/okhttp-gson/api.mustache)). Unfortunately it's hard to do this in a nice, maintainable way.

2020-10-26 16:18 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
> +  public static class MultiSubnetsStepFlight extends GoogleProjectCreationFlight {
instanceOf generic type is not allowed. Not sure how we can do this. One possible solution is  addeding a static method in the class something like setClazz(), and each class call it. For other flights, the ErrorCreateProjectFlight inserts Latch and an error steps, not sure how much we will need to modify to make the class more generic to support this

2020-10-26 17:48 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/GoogleUtils.java
> +      return true;
hmmm, consider whether we want to elevate the 403/404 to the function name or as an input parameter.

2020-10-26 17:53 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
> +  public static class MultiSubnetsStepFlight extends GoogleProjectCreationFlight {
Last try for multi -instance
```
public static class MultiInstanceStepFlight extends GoogleProjectCreationFlight {
  private final Class<? extends Step> multiStepClazz;
  public MultiInstanceStepFlight(Class<? extends Step> multiStepClazz) {...}
...
  if (multiStepClazz.isInstance(step))
...
```
I think for the other flights with latches and steps it's worth at least extending GoogleProjectCreationFlight and adding additional steps (all not in this PR please). Consider whether there are other creative solutions like this for overriding `addStep`, or what support for this we could add to the Stairway library.

2020-10-26 17:56 UTC, wchamber approved these changes

2020-10-26 17:56 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/GoogleUtils.java
> +  public interface CowExecute<R> {
I like your `CloudExecute` suggestion. Maybe, `/** A Google cloud operation that's expected to throw a IOException. See {@link GoogleUtils#resourceExists}. */ `

2020-10-26 17:56 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/GoogleUtils.java
> +  public static <R> Optional<R> getResource(CowExecute<R> execute) throws IOException {
add javadoc for this as well. Ok to have `resourceExists` reference this or vice versa to avoid repeating the same documentation.

2020-10-26 18:24 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
> +  public static class MultiSubnetsStepFlight extends GoogleProjectCreationFlight {
I don't think way gona work as well. Flights are not instantiated in RBS. All RBS did is tell Stairway the Flight class and inputMap.  And for latches and all stuff, that is only used in one test, and we can further if we have more tests which needs similar setup... For now, I don't think there will be a new test which needs that in the near future.

2020-10-26 19:13 UTC, merged