[PF-143] delete resource flight
DataBiosphere/terra-rbs pull request #39
Opened 2020-10-29 19:25 UTC by yonghaoy

2020-10-29 20:07 UTC, wchamber requested changes

2020-10-29 20:07 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/InitialResourceDeletionStep.java
> +        inputMap.get(FlightMapKeys.CLOUD_RESOURCE_UID, CloudResourceUid.class))) {
Updating the resource state in the same rbsDao function is awkward here. Consider splitting modify the resource state from other changes to resources. We never want this to change the cloud resource id, but our rbsDao API forces that to be possible.

2020-10-29 20:07 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/DeleteProjectFlightIntegrationTest.java
> +                    new bio.terra.rbs.generated.model.Network().enableNetworkMonitoring(true)));
why does this test need to mess with the network config?

2020-10-29 20:07 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/DeleteProjectFlightIntegrationTest.java
> +    Resource resource = rbsDao.retrieveResources(pool.id(), ResourceState.READY, 1).get(0);
this is kind of funny, we do the same retrieve resources after this call at the call site. Why not have this take the resource as the argument instead of the pool?

I think we can also get around the awkward retrieving exactly one ready resource from the pool id by looking at the Stairway FlightState#getResultMap. The result map should have the resource id that was stored during flight execution.
Maybe change that for this test and the CreateProjectFlightIntegrationTest.

2020-10-30 14:22 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/resource/flight/DeleteProjectStep.java
> +    return StepResult.getStepResultSuccess();
Changed to fatal. 
But I feel that is not just _we can not undo deleting_, it is also we _don't need to undo deleting_.

2020-11-02 15:46 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/resource/flight/InitialResourceDeletionStep.java
> +    if (resource.isPresent() && resource.get().state().equals(ResourceState.READY)) {
Changed to:  return fatal if resource is not found or state is not READY or DELETING. 
And for the question about different flight put it in deleting. Not sure how stariway works here. If there are two flights tried to cleanup the same resource. If we fail the slower one in the 1st step, seems fine to me. 
If we allow the slower one pass this steps, step2(DeleteProjectStep) should also work because we check if Project  is deleted or being deleted there. Step3(update db entity to DELETED) will have a small problem that we update the deletion timestamp again. But I don't think that a big deal. WDTY?

2020-11-02 15:46 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/resource/flight/InitialResourceDeletionStep.java
> +    // nothing we can do.
Changed to Fatal now.

2020-11-02 15:46 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/resource/flight/InitialResourceDeletionStep.java
> +        inputMap.get(FlightMapKeys.CLOUD_RESOURCE_UID, CloudResourceUid.class))) {
no longer needed

2020-11-02 15:46 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/integration/DeleteProjectFlightIntegrationTest.java
> +    Resource resource = rbsDao.retrieveResources(pool.id(), ResourceState.READY, 1).get(0);
Done

2020-11-02 16:09 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/DeleteProjectFlightIntegrationTest.java
> +                    new bio.terra.rbs.generated.model.Network().enableNetworkMonitoring(true)));
Hmm, that's not a bad idea, but I don't think this test will stay up to date. If we add more features to what makes a "full" project, we won't remember to update this test. I don't know if project deletion of  a project that has custom networks and logging is more interesting. If it really is, make the intention that this is a "full' project more obvious by a) using a private static final variable or function named "full' with a comment explaining the intention. As-is, the code doesn't explain why it's doing what it's doing.

2020-11-02 16:14 UTC, wchamber approved these changes

2020-11-02 16:14 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/InitialResourceDeletionStep.java
> +      return new StepResult(StepStatus.STEP_RESULT_FAILURE_FATAL);
extra states in the comment?

2020-11-02 16:14 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/InitialResourceDeletionStep.java
> +    // We can not undo a deletion
but we could undo changing the RBS state - we're just not going to bother to try.
If we do then undo just this step, there's nothing wrong with putting the resource back in the state it was. We just have problems if we put it back as READY when it wasn't ready to begin with. So this is more us not wanting to work too hard for a case we think is rare, I think.

2020-11-02 16:30 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/integration/DeleteProjectFlightIntegrationTest.java
> +                    new bio.terra.rbs.generated.model.Network().enableNetworkMonitoring(true)));
Created a `newFullGcpConfig`

2020-11-02 22:00 UTC, merged