[PF-125] Initial Pool Config for RBS
DataBiosphere/terra-rbs pull request #4
Opened 2020-09-29 15:32 UTC by yonghaoy

2020-09-29 17:43 UTC, wchamber requested changes

2020-09-29 17:43 UTC, wchamber commented on build.gradle
> +            srcDir "config/"
I think the config directory should just go under `resources`. e.g. `resources/config`

2020-09-29 17:43 UTC, wchamber commented on src/main/config/resource_schema.yaml
> +        enabledApis:
add descriptions for all of the properties

2020-09-29 17:43 UTC, wchamber commented on src/main/resources/api/service_openapi.yaml
> +    Pools:
why is the pools in service_openapi, but the resource configs in resource schema?

2020-09-29 17:43 UTC, wchamber commented on src/test/java/bio/terra/rbs/resource/PoolSchemaTest.java
> +        }
I think most of this ends up in non-test code eventually, but it's ok to start with it here in tests.

2020-09-29 18:50 UTC, yonghaoy commented on build.gradle
> +            srcDir "config/"
I started with resources/ then I checked the AoU code with Greg. This is what they have, and a better pattern I think based on Greg's feedback. I am fine with any. Let's check with @gjuggler ?

2020-09-29 18:52 UTC, yonghaoy commented on src/main/resources/api/service_openapi.yaml
> +    Pools:
Pools is special thing for RBS. `ResourceConfig` is terra common thing. 
In my mind model, RBS just uses the common` terra resource config` to construct RBS pool.

2020-09-29 18:52 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/resource/PoolSchemaTest.java
> +        }
Yup, I will move some of things in my next loading config PR

2020-09-29 18:57 UTC, gjuggler commented on build.gradle
> +            srcDir "config/"
Sorry, I think we'd gotten our lines crossed. I think I was trying to make the point that Isaac was recently re-working Workspace Manager to house its application YAML config files under the resouces/config directory for tidiness, rather than directly under the resources directory ([link](https://github.com/DataBiosphere/terra-workspace-manager/blob/afb7ed97d4bd17fb30118030aff9fe8f1fb6c66d/src/main/resources/config/application-alpha.yml)). Not relevant to this PR.

2020-09-29 19:00 UTC, yonghaoy commented on build.gradle
> +            srcDir "config/"
ah, sorry, I heard you mentioned the config/ dir and I found that is AoU has here:
https://github.com/all-of-us/workbench/blob/master/api/build.gradle#L312
And 
https://github.com/all-of-us/workbench/tree/master/api/config? 
Let me change it back. Thanks!

2020-09-29 19:06 UTC, yonghaoy commented on build.gradle
> +            srcDir "config/"
Done

2020-09-29 19:13 UTC, gjuggler commented on build.gradle
> +            srcDir "config/"
Oh yeah – that's a totally different thing. AoU uses a mostly-homegrown setup for loading much of its application config. It has some benefits & drawbacks... wld be happy to chat through those at some point, though I think sticking with what Spring supports by default is still probably the right approach.

2020-09-29 19:14 UTC, yonghaoy commented on src/main/config/resource_schema.yaml
> +        enabledApis:
Done

2020-09-29 19:28 UTC, wchamber approved these changes

2020-09-29 19:28 UTC, wchamber commented on src/test/java/bio/terra/rbs/resource/PoolSchemaTest.java
> +      ImmutableList.of("src/main/resources/config/dev/");
I think `"config/dev"` should work here. I think it's generally better to access what's under `resources/` without any preceeding directories.

2020-09-29 19:39 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/resource/PoolSchemaTest.java
> +      ImmutableList.of("src/main/resources/config/dev/");
Having different folders for pool config and resource config will make our code logic simpler. If we put everything right under `config/dev`. Our code need to have the file name check like:
```
if(fileName.equals(poolConfig)) {
   // poolSchema process
} else {
  // resource config stuff.
}
```
And not sure if we need to introduce some extra naming patterns to restrict resource config name then.
In the current model it will work if we have extra stuff(e.g., config pull scripts, other yaml files) we want to put under dev/ directory. resource-config will only contains resource configs. And `dev/` root may have pool config with extra stuff.

2020-09-29 19:53 UTC, wchamber commented on src/test/java/bio/terra/rbs/resource/PoolSchemaTest.java
> +      ImmutableList.of("src/main/resources/config/dev/");
I think you misunderstood my comment. I was suggesting replacing `"src/main/resources/config/dev/"` with `"config/dev/". That's all.

I'm not really worried about our ability to distinguish pool/resource configs from all the extra stuff. Once we have extra stuff, let's worry about that with more directories or naming conventions.

2020-09-29 22:11 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/resource/PoolSchemaTest.java
> +      ImmutableList.of("src/main/resources/config/dev/");
Done

2020-09-30 16:37 UTC, gjuggler approved these changes
Handful of nitpicks, but this looks like a good start!

2020-09-30 16:37 UTC, gjuggler commented on src/main/resources/api/service_openapi.yaml
> +        resourceConfigName:
[no action] Just thinking aloud. I suspect eventually we may find it convenient for a pool config to be able to specify a JSON-like structure of overrides that will get merged with the named resource config in order to produce the final pool configuration. This may eventually give us the right balance of customizability vs. conciseness. But this should become clear enough once things are in actual usage anyway...

2020-09-30 16:37 UTC, gjuggler commented on src/main/resources/api/service_openapi.yaml
> +        poolName:
[non-opt] Can you add a description field to each of these properties? This should be the canonical place where these fields are defined, so it's important to document what they mean sooner than later.

(Concrete question I have: for the "version" field, is that meant to be a version string for the pool config itself, or is it meant to specify which version of the resource config to load? Ideally a description string would clarify that.)

2020-09-30 16:37 UTC, gjuggler commented on src/main/resources/config/dev/pool_schema.yml
> +# RBS Pools Schema in dev encironment
Terminology nit: the object is named PoolConfig, so for consistency this file should probably be named pool_config.yml and this comment should be updated.

2020-09-30 16:37 UTC, gjuggler commented on src/main/resources/api/service_openapi.yaml
>                  items:
Kind of silly question on naming: do we have a clear pattern for kebab-case vs. snake_case for YAML files like this? Is there a reason you went one way or another? Just curious...

2020-09-30 16:37 UTC, gjuggler commented on src/main/resources/config/dev/resource-config/aou_ws_0_0_1.yml
> +    - "dns.googleapis.com"
nit: alphabetize this entry

2020-09-30 16:37 UTC, gjuggler commented on .github/workflows/test.yml
> +# This workflow will build a Java project with Gradle
Was this workflow file copied from some source (e.g. in POC repo or Janitor)? If so, it may be worth adding a comment line indicating its provenance, just for posterity.

2020-09-30 16:37 UTC, gjuggler commented on src/main/resources/config/resource_schema.yaml
> +  title: Terra Resoure Buffer Service Resource Config
spelling nit: s/resoure/resource/

2020-09-30 16:37 UTC, gjuggler commented on src/main/resources/config/dev/resource-config/aou_ws_0_0_1.yml
> +  projectIdPrefix: "aou_rw_dev"
[nit] Not that it matters a whole lot at this stage, but AoU uses dashes in its prefix. And their dev environment is called test. So probably "aou-rw-test" would be best.

2020-09-30 16:37 UTC, gjuggler commented on src/main/resources/config/resource_schema.yaml
> +            The created project name prefix.
nit: Google calls this "project ID", so we should snap to that terminology. It may also be helpful to give an example prefix and corresponding full project ID, e.g. "aou-rw-test" and "aou-rw-test-abc123" (or whatever we think our initial naming scheme may be... though this may change, as we're still having some discussion w/ product on what this should look like).

2020-09-30 16:37 UTC, gjuggler commented on src/main/resources/config/resource_schema.yaml
> +            List of APIs enable
wording nit: "APIs to enable"

2020-09-30 22:25 UTC, yonghaoy commented on src/main/resources/config/resource_schema.yaml
> +            The created project name prefix.
Good point! Done

2020-09-30 22:26 UTC, yonghaoy commented on src/main/resources/config/dev/resource-config/aou_ws_0_0_1.yml
> +  projectIdPrefix: "aou_rw_dev"
Done

2020-09-30 22:28 UTC, yonghaoy commented on .github/workflows/test.yml
> +# This workflow will build a Java project with Gradle
Done

2020-09-30 23:21 UTC, yonghaoy commented on src/main/resources/api/service_openapi.yaml
> +        resourceConfigName:
Good point, I will keep that in mind! For now, as we discussed, rbs loads folder of files, and the folder is the env variable.

2020-09-30 23:25 UTC, yonghaoy commented on src/main/resources/api/service_openapi.yaml
> +        poolName:
Done for description. And as we discussed, for now, I remove version from both resource config and pool config.
So updating pool config workflow is something like:
1. Add new resource config file with different name.
2. Add new pool config like 
```
poolName: pool_v2
resourceConfigName: newConfigName
```
3. RBS treat this is creating pool not updating existing pool. 

That is what I current thought, but that need more thoughts and discussion. I owe a README section, and will add when final decision is made.

2020-10-01 14:40 UTC, merged