[PF-218]: Creates storage logs
DataBiosphere/terra-rbs pull request #49
Opened 2020-11-05 01:55 UTC by yonghaoy

This has 180 days life cycle and an WRITER ACL. 
See: https://github.com/broadinstitute/gcp-dm-templates/blob/eeee90fa4619b273d07206a867b01914cdeb0a30/templates/project.py#L165

2020-11-05 14:36 UTC, wchamber requested changes

2020-11-05 14:36 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateBucketStep.java
> +public class CreateBucketStep implements Step {
Fix the comment. Improve the class name. This is not a step to create a generic bucket, it's specifically for storage logs.
Make sure the javadoc description for this class includes why we want to do such a thing.

2020-11-05 14:36 UTC, wchamber commented on src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
> +  private void assertBucketExists(Project project) throws Exception {
assertLogStorageBucketExists?

2020-11-05 15:32 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateBucketStep.java
> +public class CreateBucketStep implements Step {
Done. I was thinking let this steps handles all buckets creation. But we can have make each step creates one bucket if we have more..

2020-11-05 16:01 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateStorageLogBucketStep.java
> + * <p>See <a href="https://cloud.google.com/storage/docs/access-logs">Storage logs introduction</a>
per the link, don't we have to do step 3 of enabling logging on the bucket? From my understanding of this link, this is how to allow access logs for the bucket to be written. But the comments on Deployment Manager are about logging GCE stuff to this bucket. What is this bucket really for?

2020-11-05 20:01 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateStorageLogBucketStep.java
> + * <p>See <a href="https://cloud.google.com/storage/docs/access-logs">Storage logs introduction</a>
Just checked with Doug, the DM comment is copt/paste error from export bucket:
https://github.com/broadinstitute/gcp-dm-templates/blob/eeee90fa4619b273d07206a867b01914cdeb0a30/templates/project.py#L117
we enable logging on the workspace bucket when it is created, not this storage log bucket. The bucket here is where are logs are written. We do step 1 and 2 here, step 3 is in the workspace bucket. 

Changed the comment little bit

2020-11-05 22:10 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/resource/flight/CreateStorageLogBucketStep.java
> + * <p>See <a href="https://cloud.google.com/storage/docs/access-logs">Storage logs introduction</a>
added comment

2020-11-06 14:35 UTC, wchamber approved these changes

2020-11-06 14:35 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/pool/GcpResourceConfigValidator.java
> +  private static final List<String> REQUIRED_SERVICES =
not related to this PR - but if we update validation, we need to make sure old deactivated pools don't need to be modified. Just thought of that, I don't know if that's already the case.

2020-11-06 14:44 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/pool/GcpResourceConfigValidator.java
> +  private static final List<String> REQUIRED_SERVICES =
this validate configs loaded from file. And the file only has activate pool. Should be fine

2020-11-06 14:44 UTC, merged