[PF-126]
DataBiosphere/terra-rbs pull request #5
Opened 2020-10-02 17:44 UTC by yonghaoy

2020-10-05 19:50 UTC, wchamber requested changes

2020-10-05 19:50 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/pool/PoolService.java
> +    Map<String, Integer> poolsToDelete = mapDifference.entriesOnlyOnLeft();
Could we just use `Set<String>` of sets of pool names instead of `Map<String, Integer>`? I know eventually we need to update pool sizes, but I think it's still simpler to look at the 3 cases (in parsed only, in database only, in both) and handle them differently.

2020-10-05 19:50 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/pool/PoolService.java
> +    List<Pool> activatePools = rbsDao.retrievePools(PoolStatus.ACTIVE);
I think this means we can never re-activate a pool. Is that what we want? That could lead to weird states where multiple pools have the same names.
(should unique names be a database constraint?)

2020-10-05 19:50 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/pool/PoolService.java
> +    Map<PoolConfig, ResourceConfig> parsedPoolConfigs =
I'm not sure this `Map` is the most helpful. in createPools we have ` Map<String, Integer> poolsToCreate, Map<PoolConfig, ResourceConfig> parsedPools` where we need to go from the key of poolsToCreate to the key+value of parsed pools.
WDYT about List<PoolConfig> and also a Map<ResourceConfigId, ResourceConfig>? Or do we want to make even stronger constraints on PoolConfig name uniqueness?

2020-10-05 19:50 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/pool/PoolService.java
> +  public static Map<PoolConfig, ResourceConfig> loadPoolConfig(String folderName) {
Why is this `public`? Should PoolSchemaTest be in the same package as this?

2020-10-05 19:50 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/pool/PoolService.java
> +  /** Parse and load {@link PoolConfig} and {@link ResourceConfig} from file. */
It feels a little funny to me to have this deserialization logic in the same class that reconciles what's loaded with what's in the database. Deserialization feels like a lower level concern, and crossing levels is a bit of a smell. Maybe split the folder/file/parsing into a separate class? Fine to rely on the concrete implementation for now, but I think eventually we'd want to inject the parsed config into `PoolsService` for testing reconciling parsed/database pools.

2020-10-05 19:50 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/pool/PoolService.java
> +          String.format("Failed to parse pool schema for folder %s", folderName), e);
I think we should throw IOException from our load/parse function. If we want to wrap the message/exception with what file/folder operation failed that's fine. But let's a higher level decide if it should be an unchecked exception.

2020-10-05 19:50 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/pool/PoolService.java
> +    // Parse PoolConfig
`// Do something` comments are generally a good indicator that you want helper functions, e.g.
`Pools parsePools(String folderName)`
ditto others

2020-10-05 19:50 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/pool/ResourceConfigTypeVisitor.java
> +    throw new InvalidPoolConfigException(String.format("Invalid resource config for %s", resource));
This smells to me. The ResourceConfigVisitor<R> signature promises that we can always return an R, but this throws an unchecked exception. This is surprising behavior from just looking at signatures. Consider whether this should implement `ResourceConfigVisitor<Optional<ResourceType>>` or if we want to change ResourceConfigVisitor to do something else for this null case.

2020-10-05 19:50 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/pool/ResourceConfigTypeVisitor.java
> +    return ResourceConfigVisitor.visit(resourceConfig, this);
Is `new ResourceConfigTypeVisitor().accept(resourceConfig)` any easier than `ResourceConfigVisitor.visit(resourceConfig, new ResourceConfigTypeVisitor())`? Do we want a function with a default implementation on the interface?

2020-10-05 20:23 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/pool/PoolService.java
> +    List<Pool> activatePools = rbsDao.retrievePools(PoolStatus.ACTIVE);
Good point, after re-activate a pool(or just create a pool with the duplicate name), there would be multiple pools with the same name. 
Changed name in db to unique

2020-10-05 20:25 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/pool/PoolService.java
> +  public static Map<PoolConfig, ResourceConfig> loadPoolConfig(String folderName) {
I feel resourceSchemaTest shouldn't be this package because that test is to validate resource configs are valid for all environment. The actual package it want to test is `src/main/resources`

2020-10-05 20:36 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/pool/PoolService.java
> +  /** Parse and load {@link PoolConfig} and {@link ResourceConfig} from file. */
I think I am still not sure the name and package this class should be. It's name is PoolService and will handle Pool Update/Delete/Create.
The only function it does in the short term is the `initialize` method, and it will:

1. deserialize config
2. Calculate the config change
3. Do pool update. 
 deserialize is here because I don't feel this is lower level since it is will just used by this function. 
Another options is we change PoolService to PoolCompoment just like the StairwayCompoment, and has` initialize()` function.  I have it here because I feel it is similar to MigirateService, might be good to chat offline about this?

2020-10-05 20:38 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/pool/ResourceConfigTypeVisitor.java
> +    return ResourceConfigVisitor.visit(resourceConfig, this);
ah, good point, having this because i though that is a standard Java visitor pattern... Removed this.

2020-10-06 14:23 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/pool/PoolService.java
> +  /** Parse and load {@link PoolConfig} and {@link ResourceConfig} from file. */
created a helper class to have file processing logic.

2020-10-06 14:27 UTC, yonghaoy commented
@wchamber  Hi Will, all comments are addressed, and things change a lot.
Chang log:
1. Remove UUID PoolId and rename PoolName to poolId, now we have PoolId as string and loaded from file
2. Change the calculation logic to Set<Ids> allIds as what we discussed
3. Different class to handle PoolConfig Loading
PTAL, thanks

2020-10-06 15:18 UTC, wchamber requested changes

2020-10-06 15:18 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/pool/PoolService.java
> +          poolsToUpdateSize.put(dbPool.id(), configPool.poolConfig().getSize());
It's an odd assymetry that the other two cases add pools to a list ,bt this one does validation and adds it to a list. Instead of having the third list be `poolsToUpdatesSize`, what if we had `duplicatePools` with a function to `reconcileDuplicates` that did the throw or update size if necesary?

2020-10-06 15:18 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/pool/PoolWithResourceConfig.java
> +  }
Consider expanding the PoolConfig into this class, i.e. have the PoolId, size, and ResourceConfig. Right now the resourceConfigName in PoolConfig is duplicate information with wwhat's in ResourceConfig. If we're already making a class, let's make it a simpler class that has exactly what we need.

2020-10-06 15:18 UTC, wchamber commented on src/main/resources/api/service_openapi.yaml
> +            The unique id of the pool.
nit: `A unique id for the pool. No two pools can ever have the same id. Any string is allowed.`

2020-10-06 15:18 UTC, wchamber commented on src/test/java/bio/terra/rbs/service/pool/PoolServiceTest.java
> +    String poolId = "poolId";
Make this a `PoolId` instead of a string. That's how it's always used. Dito other test.

2020-10-06 15:18 UTC, wchamber commented on src/test/java/bio/terra/rbs/service/pool/PoolConfigLoaderTest.java
> +public class PoolConfigLoaderTest extends BaseUnitTest {
also have a success case test?

2020-10-06 15:20 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/pool/PoolService.java
> +          poolsToUpdateSize.put(dbPool.id(), configPool.poolConfig().getSize());
Hmm, I guess the ordering is important. We want to finish all validation before doing any database updating. Maybe just add a comment to that effect and leave it. And add a test that nothing is changed for each validation failure case.

2020-10-06 15:21 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/pool/PoolService.java
> +          poolsToUpdateSize.put(dbPool.id(), configPool.poolConfig().getSize());
Or wrap it all in a single DB transaction to handle this for us and be less error-prone.

2020-10-06 18:52 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/pool/PoolService.java
> +          poolsToUpdateSize.put(dbPool.id(), configPool.poolConfig().getSize());
(1) The code structure like this is because we are using one for loop to calculate the all conditions. Some condition is allowed and needs DB operation, some conditions is not allowed and we should error it out. 
Like the last else {} can be 
```
else if(poolId=configId && poolResourceConfig != parsedConfig) {
} else if(poolId=configId && poolSize != parsedSize) {}
```
From this point, I think it make sense. 
 It is just for now, only have validation for duplicated Pools.
(2) Added some comments. 
(3) Sorry, why we want all in one DB transaction? After validation, would we want insert fail also rollback update operation? 
(4) I already have test for assertThrows(RuntimeException) Add one line below to verify Pool stays the same.

2020-10-06 18:52 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/pool/PoolWithResourceConfig.java
> +  }
Having this class is just an optimization of using Pair. I don't think we gona need this class anywhere else after parse it.  And I hope there is not too many similar objects because that is confusing.
Expanding this object and add more customized logic feels overkill and add unnecessary complexity. 
WDTY?

2020-10-06 18:52 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/service/pool/PoolConfigLoaderTest.java
> +public class PoolConfigLoaderTest extends BaseUnitTest {
I feel we already have PoolSchemaTest in which test success logic already. 
Do we want to add another success case which start from middle of that test logic?

2020-10-06 18:52 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/service/pool/PoolServiceTest.java
> +    String poolId = "poolId";
ditto the question of having `PoolId`: I don't feel we get too much value of having this object after we have `Pool`

2020-10-06 18:52 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/pool/PoolService.java
> +        Maps.uniqueIndex(rbsDao.retrievePools(PoolStatus.ACTIVE), pool -> pool.id().toString());
Done

2020-10-06 19:07 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/pool/PoolConfigLoader.java
> +            objectMapper.readValue(resource.getInputStream(), ResourceConfig.class);
That's not always going to be sufficient, (project prefix only has specific characters, valid region), but we can wait until we get there.

2020-10-06 19:10 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/pool/PoolService.java
> +    Set<String> allPoolIds = Sets.union(activatePoolMap.keySet(), parsedPoolConfigMap.keySet());
I disagree that `PoolId` is a db layer thing. I'd like `PoolId` to be an RBS business logic thing. When a request comes in asking for a resource from a pool name, we turn that to a `PoolId`. Yes, our DB layer returns things in terms of our business logic terminology: that's convenient. The DB layer translates that business logic layer to its internal representation - text column in SQL row.
We're going to want to uniquely identify pools across RBS. Let's not stringly type that idea, let's give it a concrete type `PoolId`.

2020-10-06 19:12 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/pool/PoolService.java
> +          poolsToUpdateSize.put(dbPool.id(), configPool.poolConfig().getSize());
3) Maybe? Otherwise we get into a really weird halfway state where the DB has some but not all pools updated. Maybe I only want to increase the size of a pool because I'm removing an old one.
All or nothing is certainly easier to reason about. WDYT?

2020-10-06 19:16 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/pool/PoolWithResourceConfig.java
> +  }
I don't think there's enough custom logic or complexity for it to really be overkill. Up to you ultimately, but I really like my types to constrain me to good behavior. Right now we can have disagreeing resouceConfigName values. The less possible you make it to represent confusing states. the only "logic" is setting some fields in this create method. We don't need to change it's signature.

2020-10-06 19:17 UTC, wchamber commented on src/test/java/bio/terra/rbs/service/pool/PoolConfigLoaderTest.java
> +public class PoolConfigLoaderTest extends BaseUnitTest {
The PoolSchemaTest is for verifying that the committed configs parse. That's an end2end tet kind of independent of the impl. For PoolConfigLoaderTest, we should have a unit test that verifies a success. Let' shave good unit test coverage in addition to end2end tests.

2020-10-06 19:48 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/pool/PoolWithResourceConfig.java
> +  }
The 'overkill' here I mean is having a object similar to Pool but different from PoolConfig we have in openapi yaml.
The janitor's many objects looks too complicated than it should be I feel. The use of the class is just to hold PoolConfig with ResourceConfig without further processing. Unwraping `PoolConfig` into this class before wrapped into `Pool` soon to me feels like an intermediate steps we can avoid. So I'd like to keep this class simple.

2020-10-06 19:54 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/pool/PoolConfigLoader.java
> +            objectMapper.readValue(resource.getInputStream(), ResourceConfig.class);
Yeah, we can decide until we are there. 
But a side note, do we want to have config validation logic to verify all configs? And how detailed we want to reach? For example,  like billingAccountName valid, enabledApis are actual valid API names, a lot more VPC network stuff like ip address, network thing? And if we decide we want a full detailed validation, the code logic requires a lot more work than I thought before. For each field on each type, that would be big chunk of code. 
Also, I don't think we want to verify project prefix because that is upto the client, RBS will just use whatever the prefix it gives to RBS.

2020-10-06 21:10 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/pool/PoolConfigLoader.java
> +            objectMapper.readValue(resource.getInputStream(), ResourceConfig.class);
Always better to check configs earlier than later. I sure want to know if I typo'd my enabled API before I merge the config, otherwise I have to make a new config version name.
It's always a tradeoff between how hard it is to validate and the pain of getting it wrong. So yes, it's a chunk of code, but it could be a useful chunk of code depending on the complexity of each field.
Project ids can't contain unicode for example.

2020-10-06 21:24 UTC, wchamber approved these changes

2020-10-06 21:24 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/pool/PoolConfigLoader.java
> +  /** Deserialize {@link ResourceConfig} from config folder. */
doesn't look done?

2020-10-06 21:24 UTC, wchamber commented on src/main/java/bio/terra/rbs/service/pool/PoolService.java
> +        }
is there a test for this? A TODO in the test file is fine until we actually delete pools.

2020-10-06 21:24 UTC, wchamber commented on src/test/java/bio/terra/rbs/service/pool/PoolServiceTest.java
> +            newResourceConfig(new GcpProjectConfig().projectIDPrefix("aou-rw-test111")));
Add a comment to draw more attention to this line. It's pretty hard to pick out this is what's important.
Or make variables for each ResourceConfig to make it clear there's two and they're distinct.

2020-10-06 21:24 UTC, wchamber commented on src/test/java/bio/terra/rbs/service/pool/PoolServiceTest.java
> +  public void initialize_createPool() throws Exception {
can we also test the case where the pool already exists in the database?

2020-10-06 21:24 UTC, wchamber commented on src/test/java/bio/terra/rbs/service/pool/PoolServiceTest.java
> +  public void initialize_resourceConfigUpdate() throws Exception {
nit: I had a hard time figuring out what this test was verifying from it's name. Consider including the expected outcome as well as the condition.
https://engdoc.corp.google.com/eng/doc/devguide/testing/unit/best-practices.md?cl=head&polyglot=java#naming

2020-10-06 21:24 UTC, wchamber commented on src/test/java/bio/terra/rbs/service/pool/PoolServiceTest.java
> +    rbsDao.createPools(ImmutableList.of(pool));
WDYT about calling `poolService.initializeFromConfig` twice instead of creating pools directly with the dao? Maybe instead of `initializeFromConfig` it should be named `updateFromConfig`

2020-10-06 21:24 UTC, wchamber commented on src/test/java/bio/terra/rbs/service/pool/PoolServiceTest.java
> +    assertEquals(rbsDao.retrievePools().get(0), pool);
nit: use `assertThat(rbsDao.reqtrievePools(), Matchers.containsInAnyOrder(pool))` for better verification and error messages.

2020-10-06 21:24 UTC, wchamber commented on src/test/resources/application-test.yml
> +    update-pool-on-start: false
add a comment about why this is desirable

2020-10-06 22:43 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/service/pool/PoolServiceTest.java
> +    rbsDao.createPools(ImmutableList.of(pool));
Done

2020-10-06 22:47 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/service/pool/PoolServiceTest.java
> +  public void initialize_createPool() throws Exception {
Done

2020-10-06 22:48 UTC, yonghaoy commented on src/test/java/bio/terra/rbs/service/pool/PoolServiceTest.java
> +            newResourceConfig(new GcpProjectConfig().projectIDPrefix("aou-rw-test111")));
Done

2020-10-06 22:49 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/pool/PoolService.java
> +        }
Right, it would be better to add test once we have updatePool in RbsDao later. Added a TODO in test

2020-10-06 23:13 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/service/pool/PoolConfigLoader.java
> +            objectMapper.readValue(resource.getInputStream(), ResourceConfig.class);
Make sense, I may start a doc to list all validation rules for each of those field. And how we will validate them. 
And probably bring this up on tomorrow's standup.

2020-10-06 23:13 UTC, merged