[PF-196] Add cleanup_record table to track the resources published to Janitor
DataBiosphere/terra-rbs pull request #55
Opened 2020-11-12 21:32 UTC by yonghaoy

2020-11-12 22:07 UTC, wchamber requested changes

2020-11-12 22:07 UTC, wchamber commented on src/main/java/bio/terra/rbs/db/RbsDao.java
> +   *   <li>Handed out before given {@code handedOutBefore}
why do we need the instant argument?

2020-11-12 22:07 UTC, wchamber commented on src/main/java/bio/terra/rbs/db/RbsDao.java
> +  /** Inserts a record into cleanup_record table. */
Let's explain the semantics of the cleanup_record here. Why would I want to insert something into the cleanup record? When wouldn't I?

2020-11-12 22:07 UTC, wchamber commented on src/main/resources/db/changesets/20200925_initial_schema.yaml
> +          tableName: cleanup_record
add some comments about what this is for, especially since we're not planning on using it in prod.

2020-11-13 14:05 UTC, yonghaoy commented on src/main/resources/db/changesets/20200925_initial_schema.yaml
> +          tableName: cleanup_record
added

2020-11-13 14:08 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/db/RbsDao.java
> +  /** Inserts a record into cleanup_record table. */
done

2020-11-13 14:09 UTC, yonghaoy commented on src/main/java/bio/terra/rbs/db/RbsDao.java
> +   *   <li>Handed out before given {@code handedOutBefore}
I was thinking about not to publish those resources just handed out and leave some 'cache time' in RBS. But I realize that is overkill, that is overlap with Janitor's TTL

2020-11-13 15:31 UTC, wchamber requested changes
I think you forgot to push your commits. I don't see any changes.

2020-11-13 15:37 UTC, wchamber approved these changes

2020-11-13 15:37 UTC, wchamber commented on src/main/resources/db/changesets/20200925_initial_schema.yaml
> +                  unique: false
shouldn't these be unique?

2020-11-13 15:38 UTC, wchamber approved these changes
thanks!

2020-11-13 15:59 UTC, merged